# Generated by Django 5.1.6 on 2025-03-28 14:02

import django.core.validators
import django.db.models.deletion
import sewing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('atelier', 'Atelier')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register_commerce', models.ImageField(blank=True, null=True, upload_to=sewing_app.models.atelier_register_commerce_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('client', 'Client')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register_commerce', models.ImageField(blank=True, null=True, upload_to=sewing_app.models.client_register_commerce_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('business_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandeAtelierFabricStore',
            fields=[
                ('commande_fabric_id', models.AutoField(primary_key=True, serialize=False)),
                ('atelier_id', models.IntegerField()),
                ('fabric_store_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('denim', 'Denim'), ('polyester', 'Polyester'), ('wool', 'Wool'), ('custom', 'Custom Material')], default='custom', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAtelier',
            fields=[
                ('demande_id', models.AutoField(primary_key=True, serialize=False)),
                ('atelier_id', models.IntegerField()),
                ('commande_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FabricStore',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('fabric_store', 'Fabric Store')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('register_commerce', models.ImageField(blank=True, null=True, upload_to=sewing_app.models.fabric_store_register_commerce_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('materials_available', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.BigIntegerField()),
                ('role_sender', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('atelier', 'Atelier'), ('fabric_store', 'Fabric Store')], max_length=20)),
                ('receiver_id', models.BigIntegerField()),
                ('role_receiver', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('atelier', 'Atelier'), ('fabric_store', 'Fabric Store')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DemandeFabricStore',
            fields=[
                ('demande_fabric_id', models.AutoField(primary_key=True, serialize=False)),
                ('fabric_store_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande_fabric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='sewing_app.commandeatelierfabricstore')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Product', max_length=100)),
                ('owner', models.IntegerField(db_index=True)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('tshirt', 'T-Shirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('jacket', 'Jacket'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('promo', models.BooleanField(default=False)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=sewing_app.models.product_image_path)),
                ('image_list', models.JSONField(blank=True, default=list)),
                ('primary_image_index', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_ratings', models.IntegerField(default=0)),
                ('rating_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['promo'], name='product_promo_idx'), models.Index(fields=['owner'], name='product_owner_idx'), models.Index(fields=['category'], name='product_category_idx'), models.Index(fields=['rating'], name='product_rating_idx')],
            },
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('product', models.CharField(blank=True, choices=[('tshirt', 'T-Shirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('jacket', 'Jacket'), ('custom', 'Custom Order')], max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('image_command', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending', 'Pending'), ('validated', 'Validated'), ('completed', 'Completed'), ('refused', 'Refused')], db_index=True, default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.TextField()),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sewing_app.atelier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sewing_app.client')),
            ],
            options={
                'unique_together': {('id_commande', 'client', 'atelier')},
            },
        ),
        migrations.CreateModel(
            name='AdvertisementsAtelier',
            fields=[
                ('advertisement_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=sewing_app.models.advertisement_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='sewing_app.product')),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='sewing_app__owner_d11e86_idx'), models.Index(fields=['created_at'], name='sewing_app__created_f9cc2f_idx')],
            },
        ),
    ]
