# Generated by Django 5.1.6 on 2025-03-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_image_index',
        ),
    ]
