# Generated by Django 5.1.6 on 2025-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewing_app', '0002_remove_product_primary_image_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='atelier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='client',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
