# Generated by Django 5.1.6 on 2025-03-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewing_app', '0003_alter_commandes_atelier_alter_commandes_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
