# Generated by Django 5.1.6 on 2025-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewing_app', '0004_alter_commandes_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.BigIntegerField()),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_id', models.BigIntegerField()),
                ('sender_role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('atelier', 'Atelier'), ('fabric_store', 'Fabric Store')], max_length=20)),
                ('receiver_role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('atelier', 'Atelier'), ('fabric_store', 'Fabric Store')], max_length=20)),
                ('not_read_yet', models.IntegerField(default=0)),
                ('last_message_timestamp', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_message_timestamp'],
                'unique_together': {('sender_id', 'receiver_id', 'sender_role', 'receiver_role')},
            },
        ),
    ]
