# Generated by Django 5.1.6 on 2025-03-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewing_app', '0005_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
